name: coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install requirements
        run: |
          apt-get update -q -y
          apt-get install -q -y gcc g++ git nasm libgtest-dev openssl cmake

      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DGCOV=ON -DCMAKE_BUILD_TYPE=Debug -DMPI_NO_ASM=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build

      - name: Run Test
        working-directory: ${{github.workspace}}/build
        run: |
          make test || true
          ${{github.workspace}}/build/tests/benchmark || true

      - name: Upload To CodeCov
        run: bash <(curl -s https://codecov.io/bash)
